apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: immich
data:
  IMMICH_VERSION: "v3"
  DB_USERNAME: "postgres"
  DB_DATABASE_NAME: "immich"
  DB_STORAGE_TYPE: "HDD" # Optimize PostgreSQL for mechanical spinning disk
  IMMICH_DOMAIN: "immich.chaldea.foundation"
